### ISSUE TITLE
Code giao diện và xử lý tính năng Tìm tài sản và Lập thẻ Tài sản

### ISSUE THREAD

**Issue by chidokun** [chidokun/asset-mgmt#4]
Giao diện:

- **Tìm tài sản**: Là 1 page đính vào Main UI. Hiện thời code phần giao diện trước, @chidokun sẽ đính vào Main UI sau.
- **Lập thẻ Tài sản**: Là 1 form riêng.

**Comment by hoanghouit** [comment]
Done
